import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Fetch from './nodefsmodule/Fetch'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shopping Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>click here to check</h1>
      <Link href='/axiosapi'>Check</Link> */}
      <div>
        <Fetch />
      </div>
    </div>
  )
}
